# Generated by Django 4.0.4 on 2022-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=240)),
            ],
        ),
    ]
